; generated by PrusaSlicer 2.3.3+win64 on 2022-02-06 at 03:16:52 UTC

; 

; external perimeters extrusion width = 6.75mm
; perimeters extrusion width = 6.75mm
; infill extrusion width = 6.75mm
; solid infill extrusion width = 6.75mm
; top infill extrusion width = 6.00mm
; first layer extrusion width = 1.00mm

M73 P0 R0
M73 Q0 S0
M201 X400 Y400 Z400 E400 ; sets maximum accelerations, mm/sec^2
M203 X40 Y40 Z40 E50 ; sets maximum feedrates, mm/sec
M204 P400 R400 T400 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M104 S200 ; set temperature
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
G28
G1 E3
G92 E0.0
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;
;WITNESS ME
;AND DELETE AFTER HERE FOR PANCAKES
;
G92 E0.0
;0.5


G1 Z0.500 F1200.000
;AFTER_LAYER_CHANGE
;0.5
G1 X12.112 Y20.750
;TYPE:External perimeter
;WIDTH:1
M73 P4 R0
M73 Q4 S0
G1 F900.000
G1 X12.284 Y20.649 E0.03689
G1 X12.469 Y20.577 E0.07379
G1 X12.663 Y20.535 E0.11068
G1 X12.862 Y20.523 E0.14758
G1 X13.027 Y20.540 E0.17837
G1 X13.256 Y20.595 E0.22216
G1 X13.524 Y20.713 E0.27636
G1 X15.306 Y21.247 E0.62169
M73 P5 R0
M73 Q5 S0
G1 X17.089 Y21.684 E0.96236
G1 X18.892 Y22.030 E1.30304
M73 P6 R0
M73 Q6 S0
G1 X20.710 Y22.284 E1.64372
G1 X22.539 Y22.446 E1.98440
G1 X24.374 Y22.514 E2.32508
M73 P7 R0
M73 Q7 S0
G1 X26.148 Y22.490 E2.65445
G1 X26.445 Y22.523 E2.70976
G1 X26.721 Y22.598 E2.76285
G1 X26.981 Y22.716 E2.81593
G1 X27.221 Y22.873 E2.86902
M73 P8 R0
M73 Q8 S0
G1 X27.432 Y23.065 E2.92211
G1 X27.611 Y23.289 E2.97520
G1 X27.753 Y23.537 E3.02828
G1 X27.854 Y23.805 E3.08137
G1 X27.912 Y24.085 E3.13446
G1 X27.932 Y24.491 E3.20991
G1 X29.040 Y29.145 E4.09779
M73 P9 R0
M73 Q9 S0
G1 X30.034 Y33.751 E4.97215
M73 P10 R0
M73 Q10 S0
G1 X30.743 Y37.420 E5.66559
M73 P11 R0
M73 Q11 S0
G1 X30.538 Y37.391 E5.70409
G1 X29.405 Y37.134 E5.91962
G1 X28.297 Y36.786 E6.13515
M73 P12 R0
M73 Q12 S0
G1 X27.221 Y36.350 E6.35069
G1 X26.183 Y35.828 E6.56622
G1 X25.558 Y35.446 E6.70213
G1 X25.706 Y34.348 E6.90770
M73 P13 R0
M73 Q13 S0
G1 X25.834 Y32.770 E7.20167
G1 X25.877 Y31.186 E7.49564
G1 X25.834 Y29.602 E7.78961
M73 P14 R0
M73 Q14 S0
G1 X25.706 Y28.023 E8.08358
G1 X25.431 Y25.990 E8.46434
M73 P15 R0
M73 Q15 S0
G1 X23.444 Y25.543 E8.84229
G1 X21.900 Y25.274 E9.13312
G1 X20.345 Y25.080 E9.42395
M73 P16 R0
M73 Q16 S0
G1 X18.782 Y24.963 E9.71478
G1 X16.257 Y24.897 E10.18347
M73 P17 R0
M73 Q17 S0
G1 X17.143 Y27.761 E10.73970
M73 P18 R0
M73 Q18 S0
G1 X17.822 Y29.680 E11.11753
G1 X18.579 Y31.572 E11.49567
G1 X19.435 Y33.450 E11.87861
M73 P19 R0
M73 Q19 S0
G1 X19.690 Y33.846 E11.96593
G1 X19.951 Y34.170 E12.04314
G1 X20.146 Y34.461 E12.10821
G1 X20.493 Y35.160 E12.25307
G1 X20.766 Y35.657 E12.35826
M73 P20 R0
M73 Q20 S0
G1 X20.108 Y35.374 E12.49118
G1 X19.388 Y35.021 E12.64004
G1 X19.072 Y34.763 E12.71573
G1 X18.675 Y34.484 E12.80571
G1 X16.393 Y33.206 E13.29110
M73 P21 R0
M73 Q21 S0
G1 X14.572 Y32.070 E13.68940
G1 X13.859 Y31.578 E13.85017
G1 X13.458 Y31.326 E13.93796
M73 P22 R0
M73 Q22 S0
G1 X12.668 Y30.937 E14.10150
G1 X12.342 Y30.731 E14.17303
G1 X10.993 Y29.685 E14.48981
G1 X10.846 Y29.559 E14.52576
G1 X12.975 Y30.037 E14.93064
M73 P23 R0
M73 Q23 S0
G1 X13.389 Y30.214 E15.01435
G1 X13.868 Y30.390 E15.10896
G1 X14.776 Y30.626 E15.28314
G1 X15.324 Y29.941 E15.44594
M73 P24 R0
M73 Q24 S0
G1 X14.173 Y27.468 E15.95210
G1 X13.287 Y25.364 E16.37572
M73 P25 R0
M73 Q25 S0
G1 X12.486 Y23.227 E16.79924
G1 X11.914 Y21.500 E17.13678
G92 E0
M73 P26 R0
M73 Q26 S0
G1 X46.125 Y18.505 F1200.000
M73 P32 R0
M73 Q32 S0
G1 F900.000
G1 X46.130 Y18.441 E0.01199
G1 X46.160 Y18.396 E0.02192
G1 X46.212 Y18.357 E0.03398
G1 X46.278 Y18.357 E0.04629
G1 X47.471 Y18.733 E0.27850
G1 X48.283 Y18.928 E0.43347
G1 X50.270 Y19.239 E0.80662
M73 P33 R0
M73 Q33 S0
G1 X52.633 Y19.646 E1.25154
G1 X53.172 Y19.698 E1.35214
G1 X53.359 Y20.020 E1.42107
M73 P34 R0
M73 Q34 S0
G1 X54.223 Y22.182 E1.85317
G1 X54.373 Y22.950 E1.99843
G1 X54.485 Y23.378 E2.08044
G1 X54.775 Y24.182 E2.23906
M73 P35 R0
M73 Q35 S0
G1 X54.984 Y24.602 E2.32612
G1 X55.219 Y24.941 E2.40265
G1 X55.330 Y25.170 E2.44987
G1 X55.336 Y25.528 E2.51650
G1 X55.387 Y25.776 E2.56336
G1 X55.065 Y25.749 E2.62319
G1 X54.693 Y25.772 E2.69244
G1 X54.368 Y25.632 E2.75802
G1 X53.537 Y25.353 E2.92076
G1 X53.418 Y23.135 E3.33297
M73 P36 R0
M73 Q36 S0
G1 X53.307 Y22.395 E3.47192
G1 X53.401 Y20.767 E3.77447
M73 P37 R0
M73 Q37 S0
G1 X52.665 Y20.767 E3.91106
G1 X51.953 Y20.468 E4.05431
G1 X51.510 Y20.364 E4.13878
G1 X50.292 Y20.145 E4.36835
G1 X49.464 Y20.019 E4.52387
G1 X49.022 Y19.986 E4.60606
M73 P38 R0
M73 Q38 S0
G1 X48.293 Y19.983 E4.74137
G1 X47.947 Y20.536 E4.86235
G1 X48.525 Y21.438 E5.06111
G1 X48.668 Y21.728 E5.12105
G1 X48.929 Y22.436 E5.26113
G1 X49.115 Y22.830 E5.34190
M73 P39 R0
M73 Q39 S0
G1 X49.361 Y23.199 E5.42426
G1 X49.612 Y23.495 E5.49632
G1 X49.792 Y23.759 E5.55562
G1 X50.392 Y24.960 E5.80471
G1 X49.733 Y24.675 E5.93798
G1 X49.311 Y24.466 E6.02527
G1 X48.923 Y24.241 E6.10864
M73 P40 R0
M73 Q40 S0
G1 X48.515 Y23.924 E6.20449
G1 X48.011 Y23.660 E6.31004
G1 X47.564 Y23.479 E6.39945
G1 X47.192 Y23.242 E6.48139
G1 X46.399 Y22.677 E6.66201
G1 X46.351 Y22.638 E6.67338
G1 X46.757 Y22.644 E6.74861
G1 X48.150 Y22.522 E7.00822
M73 P41 R0
M73 Q41 S0
G1 X47.302 Y21.179 E7.30299
G1 X47.201 Y20.993 E7.34234
G1 X47.121 Y20.795 E7.38189
G1 X46.765 Y19.615 E7.61059
G1 X46.660 Y19.118 E7.70497
G92 E0
M73 P42 R0
M73 Q42 S0
G1 X8.527 Y19.875 F1200.000
M73 P48 R0
M73 Q48 S0
G1 F900.000
G1 X8.292 Y20.218 E0.07702
G1 X8.005 Y20.720 E0.18449
M73 P49 R0
M73 Q49 S0
G1 X7.759 Y21.245 E0.29197
G1 X7.671 Y21.484 E0.33931
G1 X6.767 Y20.943 E0.53481
G1 X5.980 Y20.419 E0.71023
G1 X5.217 Y19.860 E0.88565
G1 X4.480 Y19.269 E1.06107
M73 P50 R0
M73 Q50 S0
G1 X3.769 Y18.646 E1.23649
G1 X3.086 Y17.992 E1.41192
G1 X2.624 Y17.509 E1.53596
G1 X2.679 Y16.866 E1.65581
G1 X2.767 Y16.420 E1.74018
M73 P51 R0
M73 Q51 S0
G1 X2.891 Y15.982 E1.82456
G1 X3.051 Y15.557 E1.90893
G1 X3.246 Y15.146 E1.99331
G1 X3.475 Y14.753 E2.07768
G1 X3.741 Y14.373 E2.16378
G1 X4.166 Y15.076 E2.31618
G1 X4.678 Y15.824 E2.48436
M73 P52 R0
M73 Q52 S0
G1 X5.221 Y16.545 E2.65195
G1 X5.795 Y17.243 E2.81954
G1 X6.399 Y17.914 E2.98713
G1 X7.032 Y18.558 E3.15472
G1 X7.837 Y19.297 E3.35752
G92 E0
M73 P53 R0
M73 Q53 S0
G1 X41.144 Y16.341 F1200.000
M73 P58 R0
M73 Q58 S0
G1 F900.000
G1 X41.097 Y15.132 E0.22439
M73 P59 R0
M73 Q59 S0
G1 X41.643 Y15.788 E0.38281
G1 X42.052 Y16.221 E0.49323
G1 X42.480 Y16.634 E0.60364
G1 X42.927 Y17.027 E0.71406
G1 X43.771 Y17.672 E0.91115
M73 P60 R0
M73 Q60 S0
G1 X43.672 Y17.790 E0.93976
G1 X43.541 Y18.004 E0.98621
G1 X43.434 Y18.263 E1.03823
G1 X42.580 Y17.578 E1.24145
G1 X41.819 Y16.936 E1.42621
G92 E0
G1 X37.473 Y18.316 F1200.000
M73 P61 R0
M73 Q61 S0
G1 F900.000
G1 X37.066 Y18.275 E0.07601
G1 X36.387 Y18.149 E0.20412
G1 X35.721 Y17.966 E0.33222
M73 P62 R0
M73 Q62 S0
G1 X35.073 Y17.730 E0.46033
G1 X34.446 Y17.440 E0.58844
G1 X34.165 Y17.281 E0.64830
G1 X34.127 Y15.663 E0.94865
G1 X34.127 Y13.656 E1.32109
M73 P63 R0
M73 Q63 S0
G1 X34.187 Y11.107 E1.79430
G1 X32.709 Y10.666 E2.08064
M73 P64 R0
M73 Q64 S0
G1 X31.706 Y10.432 E2.27178
G1 X30.690 Y10.262 E2.46292
G1 X29.665 Y10.154 E2.65405
M73 P65 R0
M73 Q65 S0
G1 X28.243 Y10.092 E2.91820
G1 X27.814 Y10.803 E3.07225
G1 X28.726 Y12.370 E3.40872
M73 P66 R0
M73 Q66 S0
G1 X29.364 Y13.594 E3.66495
G1 X30.146 Y15.298 E4.01279
G1 X30.389 Y15.754 E4.10876
G1 X30.655 Y16.140 E4.19571
M73 P67 R0
M73 Q67 S0
G1 X30.792 Y16.435 E4.25600
G1 X31.188 Y17.575 E4.48002
G1 X30.086 Y16.975 E4.71280
G1 X29.480 Y16.464 E4.85996
G1 X29.113 Y16.190 E4.94507
G1 X27.329 Y15.063 E5.33649
M73 P68 R0
M73 Q68 S0
G1 X26.932 Y14.847 E5.42040
G1 X26.193 Y14.513 E5.57100
G1 X24.961 Y13.609 E5.85448
M73 P69 R0
M73 Q69 S0
G1 X25.322 Y13.599 E5.92151
G1 X26.148 Y13.622 E6.07494
G1 X26.509 Y13.653 E6.14212
G1 X27.321 Y13.894 E6.29933
G1 X27.717 Y13.205 E6.44678
G1 X27.379 Y12.532 E6.58658
M73 P70 R0
M73 Q70 S0
G1 X26.778 Y11.530 E6.80336
G1 X26.442 Y10.868 E6.94110
G1 X26.153 Y10.185 E7.07875
G1 X25.914 Y9.483 E7.21640
G1 X25.725 Y8.766 E7.35405
M73 P71 R0
M73 Q71 S0
G1 X25.617 Y8.199 E7.46114
G1 X27.468 Y8.501 E7.80906
G1 X30.262 Y8.897 E8.33269
M73 P72 R0
M73 Q72 S0
G1 X33.063 Y9.236 E8.85632
G1 X35.329 Y9.462 E9.27885
M73 P73 R0
M73 Q73 S0
G1 X35.527 Y10.680 E9.50784
G1 X35.870 Y12.430 E9.83867
M73 P74 R0
M73 Q74 S0
G1 X36.269 Y14.167 E10.16950
G1 X36.724 Y15.891 E10.50033
M73 P75 R0
M73 Q75 S0
G1 X37.192 Y17.461 E10.80443
G92 E0
G1 X12.177 Y16.547 F1200.000
M73 P79 R0
M73 Q79 S0
G1 F900.000
G1 X11.767 Y17.117 E0.13031
M73 P80 R0
M73 Q80 S0
G1 X11.452 Y17.493 E0.22135
G1 X11.141 Y17.827 E0.30597
G1 X10.689 Y17.279 E0.43786
G1 X9.858 Y16.333 E0.67152
G1 X8.998 Y15.413 E0.90518
M73 P81 R0
M73 Q81 S0
G1 X8.111 Y14.519 E1.13884
G1 X7.197 Y13.654 E1.37250
G1 X6.464 Y13.001 E1.55455
G1 X6.556 Y12.591 E1.63259
G1 X6.665 Y12.275 E1.69460
M73 P82 R0
M73 Q82 S0
G1 X6.801 Y11.970 E1.75662
G1 X6.966 Y11.679 E1.81863
G1 X7.133 Y11.437 E1.87333
G1 X7.957 Y11.896 E2.04833
G1 X8.509 Y12.261 E2.17111
G1 X9.040 Y12.658 E2.29430
G1 X9.548 Y13.086 E2.41748
G1 X10.030 Y13.542 E2.54066
M73 P83 R0
M73 Q83 S0
G1 X10.485 Y14.026 E2.66384
G1 X10.912 Y14.535 E2.78702
G1 X11.308 Y15.067 E2.91020
G1 X11.749 Y15.755 E3.06185
G92 E0
G1 X42.936 Y13.459 F1200.000
M73 P89 R0
M73 Q89 S0
G1 F900.000
G1 X42.978 Y13.299 E0.03075
G1 X43.087 Y13.101 E0.07271
G1 X43.251 Y12.923 E0.11750
G1 X43.415 Y12.815 E0.15395
G1 X43.691 Y12.729 E0.20775
G1 X45.866 Y14.940 E0.78327
M73 P90 R0
M73 Q90 S0
G1 X45.650 Y15.075 E0.83050
G1 X45.457 Y15.258 E0.87977
G1 X45.277 Y15.489 E0.93411
G1 X45.180 Y15.675 E0.97318
G1 X44.224 Y14.800 E1.21369
G1 X43.552 Y14.114 E1.39181
G92 E0
M73 P91 R0
M73 Q91 S0
G1 X23.048 Y8.600 F1200.000
M73 P94 R0
M73 Q94 S0
G1 F900.000
G1 X22.995 Y8.733 E0.02661
G1 X22.857 Y8.951 E0.07442
G1 X22.245 Y8.528 E0.21240
M73 P95 R0
M73 Q95 S0
G1 X21.807 Y8.184 E0.31576
G1 X21.387 Y7.819 E0.41912
G1 X20.985 Y7.433 E0.52247
G1 X20.603 Y7.027 E0.62583
G1 X20.034 Y6.334 E0.79227
G1 X20.389 Y4.626 E1.11595
M73 P96 R0
M73 Q96 S0
G1 X20.971 Y5.381 E1.29273
G1 X21.617 Y6.169 E1.48197
G1 X22.915 Y7.652 E1.84762
M73 P97 R0
M73 Q97 S0
G1 X22.962 Y7.730 E1.86446
G92 E0
G1 X24.423 Y4.924 F1200.000
G1 F900.000
G1 X24.158 Y4.678 E0.06721
G1 X23.306 Y3.808 E0.29306
M73 P98 R0
M73 Q98 S0
G1 X22.514 Y2.889 E0.51817
G1 X21.875 Y2.044 E0.71483
G1 X21.876 Y1.953 E0.73162
G1 X21.930 Y1.773 E0.76648
G1 X22.084 Y1.559 E0.81542
G1 X22.258 Y1.449 E0.85365
G1 X22.334 Y1.427 E0.86837
G1 X22.445 Y1.476 E0.89081
M73 P99 R0
M73 Q99 S0
G1 X23.113 Y1.832 E1.03132
G1 X23.700 Y2.240 E1.16402
G1 X23.959 Y2.455 E1.22651
G1 X24.470 Y2.956 E1.35920
G1 X24.690 Y3.210 E1.42170
G1 X25.110 Y3.789 E1.55439
G1 X25.222 Y3.974 E1.59449
G1 X25.173 Y4.235 E1.64374
G1 X25.104 Y4.385 E1.67437
G92 E0
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G4 ; wait
G28
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 48.42
; filament used [cm3] = 0.12
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 28s
; estimated printing time (silent mode) = 28s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,120x0,120x120,0x120
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;\n;WITNESS ME\n;AND DELETE AFTER HERE FOR PANCAKES\n;\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = G4 ; wait\nG28
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = pancake
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 0.5
; first_layer_speed = 15
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; gap_fill_speed = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 20
; inherits_cummulative = ;;"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.5
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 400,400
; machine_max_acceleration_extruding = 400,400
; machine_max_acceleration_retracting = 400,400
; machine_max_acceleration_x = 400,400
; machine_max_acceleration_y = 400,400
; machine_max_acceleration_z = 400,400
; machine_max_feedrate_e = 50,50
; machine_max_feedrate_x = 40,40
; machine_max_feedrate_y = 40,40
; machine_max_feedrate_z = 40,40
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 6
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 15
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = pancake
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = pancake
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 0
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0%
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nG28\nG1 E3\nG92 E0.0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thin_walls = 0
; threads = 12
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0%
; top_solid_infill_speed = 15
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_speed = 20
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
