; generated by PrusaSlicer 2.3.3+win64 on 2022-02-06 at 01:01:10 UTC

; 

; external perimeters extrusion width = 6.75mm
; perimeters extrusion width = 6.75mm
; infill extrusion width = 6.75mm
; solid infill extrusion width = 6.75mm
; top infill extrusion width = 6.00mm
; first layer extrusion width = 2.00mm

M73 P0 R0
M73 Q0 S0
M201 X400 Y400 Z400 E400 ; sets maximum accelerations, mm/sec^2
M203 X40 Y40 Z40 E50 ; sets maximum feedrates, mm/sec
M204 P400 R400 T400 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M104 S200 ; set temperature
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
G28
G92 E0.0
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
;LAYER_CHANGE
;Z:1
;HEIGHT:1
;BEFORE_LAYER_CHANGE
;
;WITNESS ME
;AND DELETE AFTER HERE FOR PANCAKES
;
G92 E0.0
;1


G1 Z1.000 F1200.000
;AFTER_LAYER_CHANGE
;1
G1 X12.717 Y3.251
;TYPE:External perimeter
;WIDTH:2
M73 P2 R0
M73 Q2 S0
G1 F900.000
G1 X12.923 Y2.466 E0.60258
G1 X14.206 Y2.473 E1.55529
M73 P3 R0
M73 Q3 S0
G1 X14.360 Y2.511 E1.67290
G1 X14.894 Y2.553 E2.07033
G1 X15.275 Y2.605 E2.35601
G1 X15.456 Y2.662 E2.49692
G1 X15.888 Y2.736 E2.82183
G1 X15.990 Y2.786 E2.90652
G1 X16.431 Y3.102 E3.30855
G1 X16.451 Y3.361 E3.50202
G1 X16.736 Y3.520 E3.74400
G1 X16.843 Y3.834 E3.99018
G1 X16.876 Y3.883 E4.03395
G1 X16.953 Y4.182 E4.26296
G1 X17.510 Y5.893 E5.59921
M73 P4 R0
M73 Q4 S0
G1 X18.779 Y5.304 E6.63738
G1 X19.717 Y4.988 E7.37209
G1 X20.354 Y4.827 E7.85965
M73 P5 R0
M73 Q5 S0
G1 X21.241 Y4.667 E8.52900
G1 X21.531 Y4.645 E8.74478
G1 X22.476 Y4.625 E9.44663
G1 X23.016 Y4.639 E9.84714
G1 X23.083 Y5.043 E10.15121
G1 X24.623 Y5.095 E11.29501
M73 P6 R0
M73 Q6 S0
G1 X24.711 Y5.431 E11.55306
G1 X26.472 Y5.550 E12.86275
G1 X27.708 Y5.701 E13.78732
G1 X28.660 Y5.857 E14.50344
M73 P7 R0
M73 Q7 S0
G1 X29.501 Y6.021 E15.13893
G1 X29.775 Y6.093 E15.34981
G1 X30.462 Y6.228 E15.86958
G1 X31.327 Y6.442 E16.53054
G1 X31.355 Y6.519 E16.59110
G1 X32.199 Y6.674 E17.22793
M73 P8 R0
M73 Q8 S0
G1 X32.516 Y6.773 E17.47499
G1 X32.963 Y6.882 E17.81620
G1 X34.211 Y7.272 E18.78687
G1 X34.611 Y7.378 E19.09368
G1 X34.860 Y7.489 E19.29607
G1 X35.541 Y7.610 E19.80991
G1 X36.159 Y7.465 E20.28133
G1 X36.569 Y6.960 E20.76382
M73 P9 R0
M73 Q9 S0
G1 X37.132 Y6.115 E21.51777
G1 X37.323 Y6.343 E21.73856
G1 X37.954 Y4.450 E23.21995
G1 X37.967 Y4.318 E23.31842
G1 X38.053 Y4.099 E23.49293
M73 P10 R0
M73 Q10 S0
G1 X38.013 Y3.520 E23.92370
G1 X37.508 Y2.344 E24.87346
G1 X38.790 Y2.336 E25.82485
G1 X39.693 Y2.366 E26.49613
G1 X40.016 Y2.400 E26.73664
M73 P11 R0
M73 Q11 S0
G1 X40.490 Y2.550 E27.10611
G1 X40.639 Y2.630 E27.23177
G1 X40.859 Y2.857 E27.46665
G1 X41.214 Y3.384 E27.93798
G1 X41.389 Y3.747 E28.23693
G1 X41.589 Y4.259 E28.64495
G1 X41.756 Y4.841 E29.09424
G1 X41.895 Y5.534 E29.61931
G1 X42.014 Y6.680 E30.47451
M73 P12 R0
M73 Q12 S0
G1 X42.042 Y7.340 E30.96474
G1 X42.040 Y8.309 E31.68356
G1 X41.811 Y10.323 E33.18875
M73 P13 R0
M73 Q13 S0
G1 X42.036 Y10.444 E33.37854
G1 X41.521 Y11.950 E34.56035
G1 X41.865 Y12.170 E34.86352
G1 X41.561 Y12.706 E35.32115
G1 X41.483 Y12.912 E35.48450
G1 X41.422 Y12.998 E35.56267
G1 X41.153 Y13.600 E36.05213
G1 X40.820 Y14.212 E36.56977
M73 P14 R0
M73 Q14 S0
G1 X40.512 Y14.702 E36.99919
G1 X40.480 Y14.787 E37.06634
G1 X40.372 Y14.943 E37.20722
G1 X40.213 Y15.110 E37.37848
G1 X40.150 Y15.242 E37.48726
G1 X39.988 Y15.425 E37.66887
G1 X39.869 Y15.615 E37.83523
G1 X39.496 Y16.036 E38.25261
G1 X38.614 Y16.939 E39.18956
G1 X38.169 Y17.369 E39.64858
M73 P15 R0
M73 Q15 S0
G1 X37.751 Y17.721 E40.05429
G1 X37.567 Y17.836 E40.21508
G1 X37.448 Y17.959 E40.34255
G1 X37.133 Y18.211 E40.64184
G1 X36.661 Y18.546 E41.07159
G1 X36.455 Y18.669 E41.24988
G1 X36.206 Y18.785 E41.45330
G1 X36.101 Y18.871 E41.55458
G1 X35.960 Y18.942 E41.67113
G1 X34.899 Y19.319 E42.50711
G1 X34.242 Y19.270 E42.99657
M73 P16 R0
M73 Q16 S0
G1 X34.349 Y19.625 E43.27179
G1 X33.280 Y19.157 E44.13795
G1 X32.167 Y19.043 E44.96847
G1 X31.757 Y18.960 E45.27938
G1 X31.069 Y18.879 E45.79308
G1 X30.862 Y18.822 E45.95241
M73 P17 R0
M73 Q17 S0
G1 X28.163 Y18.441 E47.97585
G1 X27.138 Y18.336 E48.74050
G1 X26.667 Y18.258 E49.09514
M73 P18 R0
M73 Q18 S0
G1 X26.013 Y18.218 E49.58120
G1 X24.365 Y18.190 E50.80523
G1 X22.759 Y18.218 E51.99754
G1 X22.137 Y18.260 E52.45977
M73 P19 R0
M73 Q19 S0
G1 X21.004 Y18.505 E53.32005
G1 X20.822 Y18.576 E53.46513
G1 X20.394 Y18.692 E53.79453
G1 X19.941 Y18.891 E54.16173
G1 X19.592 Y19.109 E54.46717
G1 X19.384 Y19.291 E54.67225
G1 X19.005 Y19.727 E55.10151
G1 X18.413 Y20.082 E55.61394
M73 P20 R0
M73 Q20 S0
G1 X18.718 Y20.934 E56.28504
G1 X18.733 Y21.022 E56.35172
G1 X18.772 Y21.572 E56.76120
G1 X18.763 Y23.207 E57.97461
G1 X17.487 Y22.464 E59.07076
M73 P21 R0
M73 Q21 S0
G1 X17.607 Y25.403 E61.25438
G1 X17.865 Y26.734 E62.26070
M73 P22 R0
M73 Q22 S0
G1 X17.462 Y27.149 E62.69031
G1 X18.048 Y28.244 E63.61248
G1 X17.813 Y28.502 E63.87164
G1 X18.245 Y29.491 E64.67267
G1 X18.393 Y30.168 E65.18730
M73 P23 R0
M73 Q23 S0
G1 X17.506 Y30.485 E65.88656
G1 X17.139 Y29.764 E66.48665
G1 X16.196 Y31.471 E67.93389
G1 X15.438 Y31.332 E68.50573
M73 P24 R0
M73 Q24 S0
G1 X15.349 Y30.714 E68.96900
G1 X15.301 Y30.573 E69.08001
G1 X15.199 Y28.934 E70.29862
G1 X14.080 Y29.693 E71.30174
M73 P25 R0
M73 Q25 S0
G1 X14.094 Y28.732 E72.01494
G1 X12.362 Y30.134 E73.66932
G1 X11.570 Y30.338 E74.27588
M73 P26 R0
M73 Q26 S0
G1 X11.257 Y29.437 E74.98391
G1 X10.485 Y29.184 E75.58715
G1 X7.927 Y29.804 E77.54084
M73 P27 R0
M73 Q27 S0
G1 X6.919 Y30.113 E78.32344
G1 X5.103 Y30.288 E79.67795
G1 X4.933 Y30.337 E79.80890
G1 X4.298 Y30.355 E80.28054
G1 X4.109 Y29.796 E80.71844
M73 P28 R0
M73 Q28 S0
G1 X3.648 Y29.345 E81.19688
G1 X3.582 Y29.035 E81.43210
G1 X3.355 Y28.934 E81.61621
G1 X3.214 Y28.626 E81.86738
G1 X3.078 Y28.213 E82.19056
G1 X3.007 Y27.759 E82.53174
G1 X2.990 Y27.516 E82.71220
G1 X2.987 Y26.688 E83.32679
G1 X3.016 Y26.158 E83.72065
G1 X3.970 Y25.996 E84.43923
M73 P29 R0
M73 Q29 S0
G1 X3.852 Y24.600 E85.47915
G1 X3.642 Y23.645 E86.20497
G1 X3.652 Y21.601 E87.72243
M73 P30 R0
M73 Q30 S0
G1 X5.042 Y23.136 E89.25963
G1 X7.017 Y22.308 E90.84926
M73 P31 R0
M73 Q31 S0
G1 X7.173 Y22.724 E91.17832
G1 X7.589 Y22.863 E91.50448
G1 X8.150 Y23.335 E92.04845
G1 X9.172 Y23.697 E92.85367
G1 X9.781 Y22.707 E93.71635
M73 P32 R0
M73 Q32 S0
G1 X10.004 Y22.199 E94.12800
G1 X10.201 Y21.633 E94.57344
G1 X10.271 Y21.297 E94.82804
G1 X10.316 Y21.231 E94.88717
G1 X10.393 Y20.868 E95.16242
G1 X10.466 Y19.872 E95.90414
G1 X10.504 Y17.644 E97.55815
M73 P33 R0
M73 Q33 S0
G1 X10.067 Y17.467 E97.90807
G1 X9.824 Y17.044 E98.27045
G1 X9.757 Y16.996 E98.33169
G1 X9.343 Y16.394 E98.87378
G1 X8.969 Y15.782 E99.40631
G1 X8.770 Y15.382 E99.73813
G1 X8.726 Y15.230 E99.85514
M73 P34 R0
M73 Q34 S0
G1 X8.702 Y15.009 E100.02009
G1 X8.712 Y14.772 E100.19638
G1 X8.741 Y14.625 E100.30788
G1 X8.908 Y14.121 E100.70137
G1 X9.744 Y12.566 E102.01248
G1 X10.350 Y13.251 E102.69106
G1 X10.762 Y10.835 E104.50965
M73 P35 R0
M73 Q35 S0
G1 X11.144 Y10.927 E104.80150
G1 X11.414 Y10.434 E105.21849
G1 X12.381 Y9.516 E106.20824
M73 P36 R0
M73 Q36 S0
G1 X12.902 Y8.892 E106.81175
G1 X13.185 Y8.484 E107.18042
G1 X13.285 Y8.386 E107.28434
G1 X13.422 Y8.129 E107.50066
G1 X13.506 Y8.023 E107.60098
G1 X13.779 Y7.499 E108.03938
G1 X13.872 Y7.143 E108.31273
G1 X13.943 Y6.506 E108.78845
G1 X13.947 Y5.791 E109.31874
M73 P37 R0
M73 Q37 S0
G1 X13.875 Y5.096 E109.83795
G1 X13.741 Y4.589 E110.22729
G1 X13.597 Y4.309 E110.46065
G1 X13.282 Y3.949 E110.81576
G1 X13.331 Y3.772 E110.95208
G92 E0
G1 X41.284 Y5.212 F1200.000
;TYPE:Solid infill
;WIDTH:2.06053
M73 P42 R0
M73 Q42 S0
G1 F900.000
G1 X39.812 Y3.740 E1.59771
G1 X39.600 Y3.703 E1.76249
G1 X39.367 Y3.695 E1.94149
M73 P43 R0
M73 Q43 S0
G1 X39.410 Y4.306 E2.41170
G1 X39.281 Y4.636 E2.68374
G1 X39.271 Y4.733 E2.75882
G1 X39.002 Y5.540 E3.41170
G1 X40.697 Y7.236 E5.25192
M73 P44 R0
M73 Q44 S0
G1 X40.701 Y8.231 E6.01570
G1 X40.536 Y9.685 E7.13852
G1 X38.349 Y7.499 E9.51148
M73 P45 R0
M73 Q45 S0
G1 X37.835 Y9.042 E10.75993
G1 X37.210 Y8.295 E11.50715
G1 X36.905 Y8.665 E11.87513
M73 P46 R0
M73 Q46 S0
G1 X40.127 Y11.887 E15.37179
M73 P47 R0
M73 Q47 S0
G1 X39.913 Y12.513 E15.87953
G1 X40.115 Y12.642 E16.06334
G1 X39.952 Y13.006 E16.36931
G1 X39.664 Y13.536 E16.83235
G1 X39.471 Y13.842 E17.10982
G1 X34.365 Y8.735 E22.65246
M73 P49 R0
M73 Q49 S0
G1 X34.163 Y8.645 E22.82199
G1 X32.605 Y8.173 E24.07103
G1 X31.876 Y7.976 E24.65097
G1 X30.797 Y7.777 E25.49299
M73 P50 R0
M73 Q50 S0
G1 X38.329 Y15.310 E33.66862
M73 P52 R0
M73 Q52 S0
G1 X37.262 Y16.382 E34.82970
G1 X37.006 Y16.597 E35.08622
M73 P53 R0
M73 Q53 S0
G1 X27.424 Y7.015 E45.48644
M73 P56 R0
M73 Q56 S0
G1 X26.345 Y6.884 E46.31999
G1 X24.561 Y6.763 E47.69284
G1 X35.462 Y17.664 E59.52415
M73 P60 R0
M73 Q60 S0
G1 X35.388 Y17.724 E59.59741
G1 X34.717 Y17.963 E60.14363
G1 X33.719 Y17.888 E60.91216
G1 X33.625 Y17.847 E60.99072
G1 X32.966 Y17.779 E61.49867
G1 X21.219 Y6.032 E74.24830
M73 P64 R0
M73 Q64 S0
G1 X20.636 Y6.136 E74.70282
G1 X20.095 Y6.273 E75.13122
G1 X19.174 Y6.597 E75.88066
M73 P65 R0
M73 Q65 S0
G1 X29.907 Y17.330 E87.52966
M73 P68 R0
M73 Q68 S0
G1 X28.322 Y17.111 E88.75737
M73 P69 R0
M73 Q69 S0
G1 X27.316 Y17.008 E89.53345
G1 X26.907 Y16.940 E89.85202
G1 X15.239 Y5.273 E102.51484
M73 P73 R0
M73 Q73 S0
G1 X15.286 Y5.726 E102.86428
G1 X15.282 Y6.584 E103.52281
G1 X15.192 Y7.388 E104.14378
G1 X15.099 Y7.743 E104.42532
G1 X24.209 Y16.853 E114.31280
M73 P76 R0
M73 Q76 S0
G1 X22.702 Y16.880 E115.46967
G1 X21.950 Y16.930 E116.04809
M73 P77 R0
M73 Q77 S0
G1 X21.724 Y16.979 E116.22510
G1 X14.165 Y9.420 E124.42905
M73 P79 R0
M73 Q79 S0
G1 X13.968 Y9.705 E124.69466
G1 X13.359 Y10.434 E125.42416
G1 X12.954 Y10.819 E125.85304
M73 P80 R0
M73 Q80 S0
G1 X19.678 Y17.544 E133.15156
M73 P82 R0
M73 Q82 S0
G1 X19.314 Y17.704 E133.45720
G1 X18.791 Y18.030 E133.93018
G1 X18.433 Y18.344 E134.29512
G1 X18.171 Y18.646 E134.60271
G1 X11.885 Y12.361 E141.42419
M73 P84 R0
M73 Q84 S0
G1 X11.848 Y12.429 E141.48320
G1 X11.483 Y14.570 E143.15016
M73 P85 R0
M73 Q85 S0
G1 X16.987 Y20.074 E149.12377
M73 P87 R0
M73 Q87 S0
G1 X17.236 Y20.768 E149.68987
G1 X16.049 Y20.076 E150.74446
G1 X16.120 Y21.817 E152.08141
G1 X11.845 Y17.542 E156.72113
M73 P89 R0
M73 Q89 S0
G1 X11.792 Y20.099 E158.68401
G1 X16.231 Y24.539 E163.50233
M73 P91 R0
M73 Q91 S0
G1 X16.273 Y25.559 E164.28591
G1 X16.417 Y26.302 E164.86726
G1 X15.908 Y26.826 E165.42770
G1 X11.386 Y22.303 E170.33635
M73 P93 R0
M73 Q93 S0
G1 X11.251 Y22.689 E170.64990
G1 X10.970 Y23.330 E171.18651
G1 X10.525 Y24.054 E171.83877
G1 X13.755 Y27.283 E175.34424
M73 P94 R0
M73 Q94 S0
G1 X12.328 Y28.439 E176.75365
M73 P95 R0
M73 Q95 S0
G1 X12.304 Y28.371 E176.80872
G1 X12.197 Y28.336 E176.89506
G1 X8.873 Y25.012 E180.50332
M73 P96 R0
M73 Q96 S0
G1 X7.473 Y24.516 E181.64302
G1 X6.922 Y24.052 E182.19567
M73 P97 R0
M73 Q97 S0
G1 X6.588 Y23.940 E182.46644
G1 X5.603 Y24.352 E183.28576
G1 X9.335 Y28.085 E187.33661
M73 P98 R0
M73 Q98 S0
G1 X7.573 Y28.512 E188.72826
G1 X7.251 Y28.611 E188.98679
M73 P99 R0
M73 Q99 S0
G1 X4.496 Y25.856 E191.97674
G92 E0
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G4 ; wait
G28
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 302.93
; filament used [cm3] = 0.73
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 29s
; estimated printing time (silent mode) = 29s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,120x0,120x120,0x120
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;\n;WITNESS ME\n;AND DELETE AFTER HERE FOR PANCAKES\n;\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 1
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = G4 ; wait\nG28
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "- default -"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 1
; first_layer_speed = 15
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; gap_fill_speed = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 20
; inherits_cummulative = ;;"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 1
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 400,400
; machine_max_acceleration_extruding = 400,400
; machine_max_acceleration_retracting = 400,400
; machine_max_acceleration_x = 400,400
; machine_max_acceleration_y = 400,400
; machine_max_acceleration_z = 400,400
; machine_max_feedrate_e = 50,50
; machine_max_feedrate_x = 40,40
; machine_max_feedrate_y = 40,40
; machine_max_feedrate_z = 40,40
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 6
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 15
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = pancake
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = pancake
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 0
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0%
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nG28\nG92 E0.0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thin_walls = 1
; threads = 12
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0%
; top_solid_infill_speed = 15
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_speed = 20
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
