; generated by PrusaSlicer 2.3.3+win64 on 2022-02-06 at 04:05:56 UTC

; 

; external perimeters extrusion width = 6.75mm
; perimeters extrusion width = 6.75mm
; infill extrusion width = 6.75mm
; solid infill extrusion width = 6.75mm
; top infill extrusion width = 6.00mm
; first layer extrusion width = 1.00mm

M73 P0 R0
M73 Q0 S0
M201 X400 Y400 Z400 E400 ; sets maximum accelerations, mm/sec^2
M203 X40 Y40 Z40 E50 ; sets maximum feedrates, mm/sec
M204 P400 R400 T400 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M104 S200 ; set temperature
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
G28
G1 E1.5
G92 E0.0
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;
;WITNESS ME
;AND DELETE AFTER HERE FOR PANCAKES
;
G92 E0.0
;0.5


G1 Z0.500 F1200.000
;AFTER_LAYER_CHANGE
;0.5
G1 X10.464 Y1.773
;TYPE:External perimeter
;WIDTH:1
M73 P4 R0
M73 Q4 S0
G1 F900.000
G1 X10.640 Y1.652 E0.03978
G1 X10.759 Y1.606 E0.06333
G1 X11.065 Y1.548 E0.12122
G1 X11.101 Y1.493 E0.13343
G1 X11.821 Y1.413 E0.26775
M73 P5 R0
M73 Q5 S0
G1 X11.969 Y1.377 E0.29600
G1 X12.815 Y1.362 E0.45310
G1 X13.673 Y1.382 E0.61243
M73 P6 R0
M73 Q6 S0
G1 X13.851 Y1.425 E0.64634
G1 X14.384 Y1.467 E0.74563
G1 X14.904 Y1.538 E0.84300
G1 X15.010 Y1.587 E0.86461
G1 X15.357 Y1.636 E0.92961
M73 P7 R0
M73 Q7 S0
G1 X15.564 Y1.688 E0.96924
G1 X15.903 Y1.870 E1.04060
G1 X16.151 Y2.061 E1.09873
G1 X16.484 Y2.385 E1.18495
G1 X16.496 Y2.531 E1.21215
G1 X16.667 Y2.626 E1.24845
M73 P8 R0
M73 Q8 S0
G1 X16.812 Y2.919 E1.30918
G1 X16.882 Y3.122 E1.34906
G1 X16.928 Y3.192 E1.36449
G1 X17.028 Y3.580 E1.43892
G1 X17.403 Y4.732 E1.66378
M73 P9 R0
M73 Q9 S0
G1 X18.080 Y4.482 E1.79774
G1 X18.226 Y4.400 E1.82878
G1 X18.690 Y4.229 E1.92043
G1 X19.266 Y4.050 E2.03235
M73 P10 R0
M73 Q10 S0
G1 X19.767 Y3.936 E2.12779
G1 X19.944 Y3.877 E2.16232
G1 X20.946 Y3.697 E2.35137
M73 P11 R0
M73 Q11 S0
G1 X21.295 Y3.671 E2.41629
G1 X22.320 Y3.649 E2.60647
G1 X23.348 Y3.675 E2.79727
M73 P12 R0
M73 Q12 S0
G1 X23.419 Y4.105 E2.87810
G1 X25.005 Y4.158 E3.17261
M73 P13 R0
M73 Q13 S0
G1 X25.102 Y4.526 E3.24335
G1 X26.583 Y4.626 E3.51880
M73 P14 R0
M73 Q14 S0
G1 X27.904 Y4.787 E3.76571
M73 P15 R0
M73 Q15 S0
G1 X28.252 Y4.857 E3.83159
G1 X28.952 Y4.959 E3.96278
G1 X29.257 Y5.032 E4.02106
M73 P16 R0
M73 Q16 S0
G1 X29.842 Y5.133 E4.13109
G1 X30.137 Y5.210 E4.18787
G1 X30.843 Y5.349 E4.32120
G1 X31.038 Y5.410 E4.35915
G1 X31.523 Y5.511 E4.45118
M73 P17 R0
M73 Q17 S0
G1 X32.068 Y5.654 E4.55582
G1 X32.089 Y5.711 E4.56706
G1 X32.702 Y5.824 E4.68269
G1 X33.052 Y5.934 E4.75069
M73 P18 R0
M73 Q18 S0
G1 X33.506 Y6.044 E4.83736
G1 X33.652 Y6.101 E4.86640
G1 X34.625 Y6.380 E5.05436
G1 X34.829 Y6.457 E5.09489
G1 X35.297 Y6.582 E5.18458
M73 P19 R0
M73 Q19 S0
G1 X35.537 Y6.689 E5.23353
G1 X36.077 Y6.785 E5.33514
G1 X36.433 Y6.701 E5.40308
G1 X36.652 Y6.431 E5.46764
M73 P20 R0
M73 Q20 S0
G1 X36.932 Y5.687 E5.61504
G1 X36.956 Y5.413 E5.66610
G1 X37.335 Y5.450 E5.73680
G1 X37.581 Y5.030 E5.82713
M73 P21 R0
M73 Q21 S0
G1 X37.642 Y4.750 E5.88019
G1 X37.670 Y4.370 E5.95091
G1 X37.996 Y4.428 E6.01236
G1 X38.101 Y3.760 E6.13793
M73 P22 R0
M73 Q22 S0
G1 X38.179 Y3.562 E6.17728
G1 X38.151 Y3.170 E6.25025
G1 X37.925 Y2.643 E6.35677
G1 X37.243 Y2.291 E6.49914
M73 P23 R0
M73 Q23 S0
G1 X37.067 Y2.136 E6.54278
G1 X37.042 Y1.961 E6.57553
G1 X36.462 Y1.696 E6.69379
G1 X37.050 Y1.449 E6.81211
M73 P24 R0
M73 Q24 S0
G1 X37.247 Y1.404 E6.84968
G1 X37.447 Y1.316 E6.89024
G1 X37.818 Y1.274 E6.95948
G1 X38.432 Y1.242 E7.07355
G1 X39.613 Y1.236 E7.29271
M73 P25 R0
M73 Q25 S0
G1 X40.508 Y1.268 E7.45885
G1 X40.923 Y1.312 E7.53637
M73 P26 R0
M73 Q26 S0
G1 X41.526 Y1.503 E7.65373
G1 X41.742 Y1.618 E7.69912
G1 X41.859 Y1.708 E7.72650
G1 X42.147 Y2.011 E7.80414
G1 X42.292 Y2.240 E7.85439
G1 X42.362 Y2.306 E7.87218
G1 X42.558 Y2.627 E7.94210
M73 P27 R0
M73 Q27 S0
G1 X42.831 Y3.208 E8.06125
G1 X42.992 Y3.630 E8.14494
G1 X43.183 Y4.299 E8.27409
M73 P28 R0
M73 Q28 S0
G1 X43.339 Y5.079 E8.42163
G1 X43.469 Y6.329 E8.65501
M73 P29 R0
M73 Q29 S0
G1 X43.500 Y7.054 E8.78966
G1 X43.497 Y8.108 E8.98525
M73 P30 R0
M73 Q30 S0
G1 X43.452 Y8.399 E9.03981
G1 X43.390 Y9.161 E9.18161
G1 X43.284 Y9.900 E9.32021
G1 X43.579 Y10.057 E9.38209
M73 P31 R0
M73 Q31 S0
G1 X43.518 Y10.359 E9.43930
G1 X43.059 Y11.689 E9.70035
M73 P32 R0
M73 Q32 S0
G1 X43.385 Y11.911 E9.77361
G1 X43.030 Y12.804 E9.95196
G1 X42.942 Y12.959 E9.98502
G1 X42.850 Y13.201 E10.03321
M73 P33 R0
M73 Q33 S0
G1 X42.776 Y13.305 E10.05685
G1 X42.506 Y13.910 E10.17983
G1 X42.136 Y14.590 E10.32348
G1 X41.831 Y15.076 E10.42978
M73 P34 R0
M73 Q34 S0
G1 X41.792 Y15.177 E10.44985
G1 X41.616 Y15.431 E10.50734
G1 X41.480 Y15.574 E10.54383
G1 X41.419 Y15.705 E10.57073
G1 X41.225 Y15.923 E10.62483
G1 X41.100 Y16.123 E10.66859
G1 X40.668 Y16.611 E10.78962
M73 P35 R0
M73 Q35 S0
G1 X39.722 Y17.578 E11.04055
G1 X39.234 Y18.050 E11.16650
M73 P36 R0
M73 Q36 S0
G1 X38.749 Y18.458 E11.28423
G1 X38.579 Y18.564 E11.32134
G1 X38.446 Y18.702 E11.35702
G1 X37.576 Y19.344 E11.55766
M73 P37 R0
M73 Q37 S0
G1 X37.314 Y19.500 E11.61406
G1 X37.090 Y19.604 E11.65991
G1 X36.986 Y19.689 E11.68498
G1 X36.752 Y19.807 E11.73345
G1 X36.280 Y19.975 E11.82645
M73 P38 R0
M73 Q38 S0
G1 X36.288 Y21.190 E12.05204
G1 X36.339 Y21.903 E12.18465
M73 P39 R0
M73 Q39 S0
G1 X35.832 Y23.197 E12.44247
G1 X35.753 Y23.542 E12.50818
G1 X35.593 Y24.094 E12.61489
M73 P40 R0
M73 Q40 S0
G1 X35.383 Y24.697 E12.73341
G1 X35.065 Y25.481 E12.89038
M73 P41 R0
M73 Q41 S0
G1 X34.996 Y25.583 E12.91320
G1 X34.885 Y25.842 E12.96562
G1 X34.824 Y25.925 E12.98466
G1 X34.712 Y26.188 E13.03773
G1 X34.535 Y26.487 E13.10232
G1 X34.095 Y26.311 E13.19029
G1 X34.344 Y25.227 E13.39675
M73 P42 R0
M73 Q42 S0
G1 X34.470 Y24.313 E13.56789
G1 X34.554 Y23.853 E13.65468
M73 P43 R0
M73 Q43 S0
G1 X34.589 Y22.927 E13.82666
G1 X34.584 Y21.890 E14.01910
M73 P44 R0
M73 Q44 S0
G1 X34.550 Y21.496 E14.09239
G1 X34.368 Y20.178 E14.33946
M73 P45 R0
M73 Q45 S0
G1 X33.692 Y20.121 E14.46527
G1 X33.566 Y20.066 E14.49083
G1 X32.452 Y19.952 E14.69860
M73 P46 R0
M73 Q46 S0
G1 X32.015 Y19.864 E14.78136
G1 X31.271 Y19.775 E14.92039
G1 X31.050 Y19.715 E14.96282
G1 X30.196 Y19.606 E15.12274
M73 P47 R0
M73 Q47 S0
G1 X29.787 Y19.529 E15.19990
G1 X28.746 Y19.400 E15.39464
M73 P48 R0
M73 Q48 S0
G1 X28.255 Y19.320 E15.48695
G1 X27.160 Y19.207 E15.69114
G1 X26.675 Y19.127 E15.78244
M73 P49 R0
M73 Q49 S0
G1 X26.026 Y19.087 E15.90302
G1 X24.310 Y19.058 E16.22160
M73 P50 R0
M73 Q50 S0
G1 X22.640 Y19.087 E16.53150
M73 P51 R0
M73 Q51 S0
G1 X22.039 Y19.128 E16.64326
G1 X20.928 Y19.368 E16.85426
M73 P52 R0
M73 Q52 S0
G1 X20.749 Y19.438 E16.88986
G1 X20.308 Y19.557 E16.97451
G1 X19.906 Y19.734 E17.05615
G1 X19.610 Y19.919 E17.12092
G1 X19.448 Y20.061 E17.16091
G1 X19.195 Y20.338 E17.23049
M73 P53 R0
M73 Q53 S0
G1 X19.034 Y20.546 E17.27938
G1 X18.710 Y20.740 E17.34936
G1 X18.895 Y21.256 E17.45114
G1 X18.968 Y22.052 E17.59931
M73 P54 R0
M73 Q54 S0
G1 X18.962 Y23.111 E17.79583
G1 X18.915 Y23.506 E17.86980
G1 X18.860 Y23.631 E17.89508
M73 P55 R0
M73 Q55 S0
G1 X18.723 Y24.143 E17.99337
G1 X18.527 Y24.506 E18.07005
G1 X17.673 Y24.008 E18.25351
M73 P56 R0
M73 Q56 S0
G1 X17.703 Y25.517 E18.53355
G1 X17.738 Y26.050 E18.63260
M73 P57 R0
M73 Q57 S0
G1 X17.943 Y27.104 E18.83181
G1 X17.994 Y27.198 E18.85171
G1 X18.038 Y27.397 E18.88952
G1 X18.121 Y27.616 E18.93309
G1 X17.706 Y28.034 E19.04234
M73 P58 R0
M73 Q58 S0
G1 X18.177 Y28.912 E19.22727
G1 X18.342 Y29.159 E19.28239
G1 X18.051 Y29.478 E19.36253
M73 P59 R0
M73 Q59 S0
G1 X18.393 Y30.257 E19.52058
G1 X18.443 Y30.440 E19.55565
G1 X18.503 Y30.804 E19.62415
G1 X18.546 Y30.851 E19.63598
G1 X18.572 Y31.169 E19.69511
M73 P60 R0
M73 Q60 S0
G1 X18.652 Y33.475 E20.12333
M73 P61 R0
M73 Q61 S0
G1 X18.817 Y34.327 E20.28442
G1 X18.220 Y33.947 E20.41582
M73 P62 R0
M73 Q62 S0
G1 X17.806 Y33.594 E20.51672
G1 X17.401 Y33.176 E20.62474
G1 X17.170 Y32.866 E20.69657
G1 X16.672 Y31.888 E20.90024
M73 P63 R0
M73 Q63 S0
G1 X16.103 Y32.918 E21.11861
M73 P64 R0
M73 Q64 S0
G1 X15.952 Y33.304 E21.19565
G1 X15.757 Y33.988 E21.32751
G1 X15.563 Y34.941 E21.50799
M73 P65 R0
M73 Q65 S0
G1 X15.185 Y34.543 E21.60967
G1 X14.946 Y34.173 E21.69142
G1 X14.819 Y33.908 E21.74602
G1 X14.731 Y33.607 E21.80418
M73 P66 R0
M73 Q66 S0
G1 X14.662 Y33.559 E21.81983
G1 X14.539 Y33.213 E21.88788
G1 X14.369 Y32.580 E22.00959
G1 X14.310 Y32.246 E22.07238
G1 X14.267 Y31.846 E22.14718
M73 P67 R0
M73 Q67 S0
G1 X14.205 Y31.667 E22.18228
G1 X14.154 Y30.834 E22.33705
G1 X12.855 Y31.715 E22.62821
M73 P68 R0
M73 Q68 S0
G1 X12.660 Y30.984 E22.76859
G1 X11.910 Y31.603 E22.94906
M73 P69 R0
M73 Q69 S0
G1 X9.984 Y32.098 E23.31808
M73 P70 R0
M73 Q70 S0
G1 X10.179 Y31.391 E23.45414
G1 X10.180 Y31.152 E23.49849
M73 P71 R0
M73 Q71 S0
G1 X10.058 Y30.802 E23.56737
G1 X9.655 Y30.670 E23.64610
G1 X7.127 Y31.283 E24.12873
M73 P72 R0
M73 Q72 S0
G1 X5.920 Y31.652 E24.36296
M73 P73 R0
M73 Q73 S0
G1 X5.784 Y31.725 E24.39167
G1 X5.097 Y31.979 E24.52749
G1 X5.093 Y31.709 E24.57752
M73 P74 R0
M73 Q74 S0
G1 X4.107 Y31.804 E24.76121
G1 X3.911 Y31.861 E24.79925
G1 X3.259 Y31.880 E24.92018
M73 P75 R0
M73 Q75 S0
G1 X2.696 Y31.850 E25.02488
G1 X2.613 Y31.644 E25.06610
G1 X2.563 Y31.308 E25.12903
G1 X2.473 Y31.042 E25.18110
G1 X1.959 Y30.528 E25.31604
M73 P76 R0
M73 Q76 S0
G1 X1.916 Y30.328 E25.35386
G1 X1.769 Y30.262 E25.38384
G1 X1.673 Y30.095 E25.41971
G1 X1.486 Y29.680 E25.50419
G1 X1.328 Y29.200 E25.59782
M73 P77 R0
M73 Q77 S0
G1 X1.243 Y28.654 E25.70048
G1 X1.222 Y28.357 E25.75579
G1 X1.218 Y27.449 E25.92425
G1 X1.273 Y26.451 E26.10961
M73 P78 R0
M73 Q78 S0
G1 X2.214 Y26.291 E26.28675
M73 P79 R0
M73 Q79 S0
G1 X2.135 Y25.342 E26.46348
G1 X1.963 Y24.517 E26.61989
G1 X1.912 Y24.349 E26.65243
M73 P80 R0
M73 Q80 S0
G1 X1.898 Y24.034 E26.71099
G1 X1.905 Y23.308 E26.84573
G1 X1.930 Y23.079 E26.88838
G1 X2.086 Y22.325 E27.03140
M73 P81 R0
M73 Q81 S0
G1 X2.527 Y21.015 E27.28774
G1 X2.986 Y21.832 E27.46156
M73 P82 R0
M73 Q82 S0
G1 X3.104 Y21.931 E27.49015
G1 X3.162 Y22.034 E27.51200
G1 X4.090 Y23.059 E27.76869
M73 P83 R0
M73 Q83 S0
G1 X4.847 Y22.742 E27.92104
G1 X4.707 Y21.917 E28.07639
M73 P84 R0
M73 Q84 S0
G1 X5.261 Y22.076 E28.18335
G1 X5.409 Y22.159 E28.21480
G1 X5.761 Y22.284 E28.28415
G1 X6.234 Y22.544 E28.38442
M73 P85 R0
M73 Q85 S0
G1 X6.306 Y22.566 E28.39826
G1 X6.580 Y22.737 E28.45835
G1 X6.631 Y22.848 E28.48089
G1 X6.868 Y22.927 E28.52724
G1 X7.461 Y23.410 E28.66924
G1 X7.700 Y23.546 E28.72033
G1 X8.159 Y23.472 E28.80664
M73 P86 R0
M73 Q86 S0
G1 X8.443 Y23.008 E28.90758
G1 X8.653 Y22.528 E29.00483
G1 X8.843 Y21.985 E29.11144
M73 P87 R0
M73 Q87 S0
G1 X8.931 Y21.558 E29.19240
G1 X8.979 Y21.487 E29.20845
G1 X9.031 Y21.249 E29.25359
G1 X9.103 Y20.252 E29.43906
G1 X9.137 Y18.299 E29.80150
M73 P88 R0
M73 Q88 S0
G1 X8.911 Y18.208 E29.84658
M73 P89 R0
M73 Q89 S0
G1 X8.717 Y17.950 E29.90651
G1 X8.560 Y17.676 E29.96508
G1 X8.508 Y17.639 E29.97693
G1 X8.015 Y16.922 E30.13843
G1 X7.880 Y16.674 E30.19078
M73 P90 R0
M73 Q90 S0
G1 X7.778 Y16.552 E30.22029
G1 X7.596 Y16.239 E30.28756
G1 X7.350 Y15.745 E30.38985
G1 X7.277 Y15.491 E30.43898
G1 X7.242 Y15.170 E30.49896
G1 X7.255 Y14.835 E30.56105
M73 P91 R0
M73 Q91 S0
G1 X7.301 Y14.603 E30.60491
G1 X7.500 Y14.005 E30.72194
G1 X7.651 Y13.696 E30.78574
G1 X8.240 Y12.619 E31.01358
M73 P92 R0
M73 Q92 S0
G1 X8.609 Y11.414 E31.24747
M73 P93 R0
M73 Q93 S0
G1 X9.183 Y12.062 E31.40812
G1 X9.406 Y10.752 E31.65471
M73 P94 R0
M73 Q94 S0
G1 X9.500 Y10.406 E31.72121
G1 X9.623 Y10.107 E31.78127
G1 X10.085 Y10.218 E31.86952
G1 X10.213 Y9.984 E31.91893
M73 P95 R0
M73 Q95 S0
G1 X11.271 Y8.980 E32.18964
G1 X11.784 Y8.366 E32.33814
M73 P96 R0
M73 Q96 S0
G1 X12.097 Y7.913 E32.44024
G1 X12.179 Y7.833 E32.46159
G1 X12.308 Y7.591 E32.51242
G1 X12.395 Y7.482 E32.53829
G1 X12.629 Y7.032 E32.63235
M73 P97 R0
M73 Q97 S0
G1 X12.701 Y6.756 E32.68538
G1 X12.769 Y6.154 E32.79784
G1 X12.772 Y5.460 E32.92657
G1 X12.704 Y4.799 E33.04985
M73 P98 R0
M73 Q98 S0
G1 X12.589 Y4.365 E33.13322
G1 X12.496 Y4.184 E33.17097
G1 X12.308 Y3.969 E33.22401
G1 X11.988 Y3.743 E33.29666
G1 X12.080 Y3.413 E33.36027
M73 P99 R0
M73 Q99 S0
G1 X11.412 Y3.048 E33.50140
G1 X11.334 Y2.976 E33.52109
G1 X11.140 Y2.869 E33.56223
G1 X11.178 Y2.783 E33.57956
G1 X10.894 Y2.501 E33.65380
G92 E0
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G4 ; wait
G28
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 33.65
; filament used [cm3] = 0.08
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 13s
; estimated printing time (silent mode) = 13s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,120x0,120x120,0x120
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;\n;WITNESS ME\n;AND DELETE AFTER HERE FOR PANCAKES\n;\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = G4 ; wait\nG28
; ensure_vertical_shell_thickness = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "- default -"
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 0.5
; first_layer_speed = 15
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; gap_fill_speed = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 20
; inherits_cummulative = ;;"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.5
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 400,400
; machine_max_acceleration_extruding = 400,400
; machine_max_acceleration_retracting = 400,400
; machine_max_acceleration_x = 400,400
; machine_max_acceleration_y = 400,400
; machine_max_acceleration_z = 400,400
; machine_max_feedrate_e = 50,50
; machine_max_feedrate_x = 40,40
; machine_max_feedrate_y = 40,40
; machine_max_feedrate_z = 40,40
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 6
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 15
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = pancake
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = pancake
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 0
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0%
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nG28\nG1 E1.5\nG92 E0.0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thin_walls = 1
; threads = 12
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0%
; top_solid_infill_speed = 15
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_speed = 20
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
