; generated by PrusaSlicer 2.3.3+win64 on 2022-02-12 at 21:32:09 UTC

; 

; external perimeters extrusion width = 6.75mm
; perimeters extrusion width = 6.75mm
; infill extrusion width = 6.75mm
; solid infill extrusion width = 6.75mm
; top infill extrusion width = 6.00mm
; first layer extrusion width = 1.00mm

M73 P0 R0
M73 Q0 S0
M201 X400 Y400 Z400 E400 ; sets maximum accelerations, mm/sec^2
M203 X40 Y40 Z40 E50 ; sets maximum feedrates, mm/sec
M204 P400 R400 T400 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
M104 S200 ; set temperature
;TYPE:Custom
G90 ; use absolute coordinates
M83 ; extruder relative mode
G28
G1 E1.5
G92 E0.0
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
;LAYER_CHANGE
;Z:0.5
;HEIGHT:0.5
;BEFORE_LAYER_CHANGE
;
;WITNESS ME
;AND DELETE AFTER HERE FOR PANCAKES
;
G92 E0.0
;0.5


G1 Z0.500 F1200.000
;AFTER_LAYER_CHANGE
;0.5
G1 X12.247 Y3.677
;TYPE:External perimeter
;WIDTH:1
M73 P5 R0
M73 Q5 S0
G1 F900.000
G1 X12.395 Y3.568 E0.03415
G1 X12.509 Y3.525 E0.05668
G1 X12.812 Y3.467 E0.11393
G1 X12.840 Y3.423 E0.12363
G1 X12.945 Y3.403 E0.14333
G1 X13.544 Y3.336 E0.25530
M73 P6 R0
M73 Q6 S0
G1 X13.688 Y3.301 E0.28278
G1 X14.513 Y3.287 E0.43586
G1 X15.349 Y3.305 E0.59113
M73 P7 R0
M73 Q7 S0
G1 X15.522 Y3.348 E0.62418
G1 X16.044 Y3.389 E0.72123
G1 X16.496 Y3.450 E0.80597
G1 X16.684 Y3.510 E0.84259
G1 X16.992 Y3.554 E0.90025
G1 X17.193 Y3.604 E0.93860
G1 X17.388 Y3.700 E0.97903
M73 P8 R0
M73 Q8 S0
G1 X17.768 Y3.972 E1.06575
G1 X18.084 Y4.278 E1.14738
G1 X18.095 Y4.423 E1.17428
G1 X18.262 Y4.515 E1.20963
G1 X18.517 Y5.066 E1.32220
M73 P9 R0
M73 Q9 S0
G1 X18.615 Y5.443 E1.39456
G1 X18.985 Y6.580 E1.61644
G1 X19.658 Y6.331 E1.74969
M73 P10 R0
M73 Q10 S0
G1 X19.801 Y6.251 E1.77999
G1 X20.252 Y6.085 E1.86924
G1 X20.814 Y5.910 E1.97836
G1 X21.303 Y5.799 E2.07156
M73 P11 R0
M73 Q11 S0
G1 X21.475 Y5.742 E2.10522
G1 X22.453 Y5.566 E2.28952
G1 X22.793 Y5.540 E2.35272
G1 X23.792 Y5.519 E2.53828
M73 P12 R0
M73 Q12 S0
G1 X24.791 Y5.546 E2.72369
M73 P13 R0
M73 Q13 S0
G1 X24.860 Y5.964 E2.80222
G1 X26.408 Y6.016 E3.08956
M73 P14 R0
M73 Q14 S0
G1 X26.503 Y6.375 E3.15856
G1 X27.954 Y6.473 E3.42841
M73 P15 R0
M73 Q15 S0
G1 X29.242 Y6.630 E3.66933
G1 X30.265 Y6.798 E3.86160
M73 P16 R0
M73 Q16 S0
G1 X30.563 Y6.869 E3.91847
G1 X31.133 Y6.967 E4.02586
G1 X31.422 Y7.043 E4.08127
G1 X32.110 Y7.178 E4.21139
M73 P17 R0
M73 Q17 S0
G1 X33.301 Y7.475 E4.43916
G1 X33.322 Y7.531 E4.45020
G1 X33.926 Y7.642 E4.56420
M73 P18 R0
M73 Q18 S0
G1 X34.267 Y7.749 E4.63053
G1 X34.709 Y7.856 E4.71506
G1 X35.802 Y8.184 E4.92677
M73 P19 R0
M73 Q19 S0
G1 X36.002 Y8.260 E4.96637
G1 X36.457 Y8.381 E5.05387
G1 X36.693 Y8.487 E5.10176
G1 X37.223 Y8.581 E5.20168
M73 P20 R0
M73 Q20 S0
G1 X37.577 Y8.497 E5.26921
G1 X37.795 Y8.229 E5.33335
G1 X38.069 Y7.500 E5.47791
G1 X38.092 Y7.243 E5.52584
G1 X38.458 Y7.278 E5.59405
M73 P21 R0
M73 Q21 S0
G1 X38.703 Y6.860 E5.68400
G1 X38.763 Y6.584 E5.73630
G1 X38.791 Y6.204 E5.80697
G1 X39.118 Y6.230 E5.86777
M73 P22 R0
M73 Q22 S0
G1 X39.212 Y5.618 E5.98272
G1 X39.287 Y5.425 E6.02120
G1 X39.260 Y5.037 E6.09330
G1 X39.037 Y4.516 E6.19846
G1 X38.368 Y4.171 E6.33798
M73 P23 R0
M73 Q23 S0
G1 X38.200 Y4.024 E6.37949
G1 X38.176 Y3.851 E6.41185
G1 X38.011 Y3.770 E6.44605
G1 X37.967 Y3.496 E6.49739
G1 X38.104 Y3.401 E6.52839
G1 X38.370 Y3.327 E6.57952
M73 P24 R0
M73 Q24 S0
G1 X38.564 Y3.241 E6.61895
G1 X38.924 Y3.200 E6.68614
G1 X39.523 Y3.169 E6.79753
G1 X40.496 Y3.161 E6.97799
M73 P25 R0
M73 Q25 S0
G1 X41.549 Y3.195 E7.17351
G1 X41.952 Y3.237 E7.24871
G1 X42.539 Y3.423 E7.36286
M73 P26 R0
M73 Q26 S0
G1 X42.747 Y3.535 E7.40679
G1 X43.051 Y3.811 E7.48299
G1 X43.140 Y3.915 E7.50844
G1 X43.281 Y4.139 E7.55763
G1 X43.350 Y4.203 E7.57498
G1 X43.542 Y4.517 E7.64331
M73 P27 R0
M73 Q27 S0
G1 X43.744 Y4.937 E7.72978
G1 X43.954 Y5.466 E7.83542
G1 X44.149 Y6.145 E7.96648
G1 X44.301 Y6.905 E8.11023
M73 P28 R0
M73 Q28 S0
G1 X44.428 Y8.125 E8.33790
G1 X44.458 Y8.832 E8.46925
M73 P29 R0
M73 Q29 S0
G1 X44.456 Y9.870 E8.66186
G1 X44.257 Y11.619 E8.98846
M73 P30 R0
M73 Q30 S0
G1 X44.534 Y11.767 E9.04680
G1 X44.476 Y12.055 E9.10140
M73 P31 R0
M73 Q31 S0
G1 X44.027 Y13.356 E9.35678
G1 X44.345 Y13.572 E9.42807
M73 P32 R0
M73 Q32 S0
G1 X44.000 Y14.440 E9.60130
G1 X43.914 Y14.591 E9.63360
G1 X43.825 Y14.828 E9.68054
G1 X43.753 Y14.929 E9.70355
G1 X43.489 Y15.520 E9.82374
M73 P33 R0
M73 Q33 S0
G1 X43.128 Y16.183 E9.96383
G1 X42.830 Y16.657 E10.06776
G1 X42.793 Y16.756 E10.08730
G1 X42.622 Y17.002 E10.14300
M73 P34 R0
M73 Q34 S0
G1 X42.489 Y17.142 E10.17881
G1 X42.428 Y17.271 E10.20510
G1 X42.240 Y17.483 E10.25779
G1 X42.117 Y17.678 E10.30051
G1 X41.696 Y18.154 E10.41843
G1 X40.773 Y19.097 E10.66333
M73 P35 R0
M73 Q35 S0
G1 X40.298 Y19.557 E10.78619
G1 X39.825 Y19.956 E10.90089
M73 P36 R0
M73 Q36 S0
G1 X39.659 Y20.060 E10.93724
G1 X39.528 Y20.194 E10.97203
G1 X38.680 Y20.820 E11.16772
G1 X38.426 Y20.971 E11.22258
M73 P37 R0
M73 Q37 S0
G1 X38.206 Y21.074 E11.26752
G1 X38.104 Y21.157 E11.29203
G1 X37.878 Y21.271 E11.33897
G1 X37.410 Y21.438 E11.43119
G1 X37.417 Y22.633 E11.65306
M73 P38 R0
M73 Q38 S0
G1 X37.471 Y23.379 E11.79184
G1 X37.526 Y23.653 E11.84376
G1 X37.566 Y23.761 E11.86510
G1 X37.511 Y23.803 E11.87801
G1 X37.355 Y23.612 E11.92378
M73 P39 R0
M73 Q39 S0
G1 X36.976 Y24.579 E12.11645
G1 X36.738 Y25.469 E12.28745
M73 P40 R0
M73 Q40 S0
G1 X36.535 Y26.052 E12.40207
G1 X36.225 Y26.816 E12.55502
G1 X36.157 Y26.915 E12.57727
G1 X36.049 Y27.168 E12.62841
M73 P41 R0
M73 Q41 S0
G1 X35.989 Y27.249 E12.64700
G1 X35.881 Y27.506 E12.69879
G1 X35.551 Y28.081 E12.82185
G1 X35.424 Y28.262 E12.86294
G1 X35.381 Y28.363 E12.88319
G1 X35.051 Y28.831 E12.98940
M73 P42 R0
M73 Q42 S0
G1 X34.943 Y28.923 E13.01583
G1 X34.895 Y29.024 E13.03659
G1 X35.118 Y28.243 E13.18730
G1 X35.178 Y28.093 E13.21733
G1 X35.360 Y27.406 E13.34913
M73 P43 R0
M73 Q43 S0
G1 X35.544 Y26.575 E13.50706
G1 X35.666 Y25.683 E13.67418
G1 X35.748 Y25.233 E13.75902
M73 P44 R0
M73 Q44 S0
G1 X35.783 Y24.328 E13.92713
G1 X35.778 Y23.315 E14.11514
M73 P45 R0
M73 Q45 S0
G1 X35.745 Y22.930 E14.18683
G1 X35.564 Y21.626 E14.43106
M73 P46 R0
M73 Q46 S0
G1 X34.896 Y21.576 E14.55541
G1 X34.775 Y21.523 E14.57994
G1 X33.686 Y21.411 E14.78303
M73 P47 R0
M73 Q47 S0
G1 X33.259 Y21.326 E14.86380
G1 X32.533 Y21.240 E14.99946
G1 X32.318 Y21.180 E15.04087
G1 X31.483 Y21.074 E15.19709
M73 P48 R0
M73 Q48 S0
G1 X31.084 Y20.999 E15.27243
G1 X30.067 Y20.873 E15.46258
G1 X29.588 Y20.795 E15.55273
M73 P49 R0
M73 Q49 S0
G1 X28.519 Y20.684 E15.75207
G1 X28.045 Y20.606 E15.84125
G1 X27.411 Y20.568 E15.95913
M73 P50 R0
M73 Q50 S0
G1 X25.735 Y20.539 E16.27024
M73 P51 R0
M73 Q51 S0
G1 X24.104 Y20.567 E16.57288
G1 X23.516 Y20.607 E16.68221
M73 P52 R0
M73 Q52 S0
G1 X22.430 Y20.842 E16.88855
G1 X22.255 Y20.910 E16.92336
G1 X21.825 Y21.027 E17.00605
M73 P53 R0
M73 Q53 S0
G1 X21.430 Y21.200 E17.08607
G1 X21.139 Y21.382 E17.14964
G1 X20.980 Y21.521 E17.18899
G1 X20.576 Y21.995 E17.30444
G1 X20.254 Y22.188 E17.37415
M73 P54 R0
M73 Q54 S0
G1 X20.438 Y22.700 E17.47513
G1 X20.508 Y23.474 E17.61930
G1 X20.502 Y24.506 E17.81095
M73 P55 R0
M73 Q55 S0
G1 X20.457 Y24.891 E17.88271
G1 X20.403 Y25.011 E17.90723
G1 X20.270 Y25.510 E18.00311
G1 X20.170 Y25.696 E18.04219
M73 P56 R0
M73 Q56 S0
G1 X20.045 Y25.830 E18.07624
G1 X19.224 Y25.352 E18.25256
G1 X19.306 Y27.372 E18.62775
M73 P57 R0
M73 Q57 S0
G1 X19.508 Y28.410 E18.82392
M73 P58 R0
M73 Q58 S0
G1 X19.558 Y28.502 E18.84337
G1 X19.601 Y28.695 E18.88013
G1 X19.681 Y28.906 E18.92203
G1 X19.275 Y29.314 E19.02880
G1 X19.737 Y30.177 E19.21049
M73 P59 R0
M73 Q59 S0
G1 X19.844 Y30.337 E19.24611
G1 X19.877 Y30.433 E19.26501
G1 X19.612 Y30.723 E19.33795
G1 X19.948 Y31.489 E19.49301
M73 P60 R0
M73 Q60 S0
G1 X19.996 Y31.665 E19.52699
G1 X20.054 Y32.024 E19.59441
G1 X20.096 Y32.069 E19.60586
G1 X20.122 Y32.375 E19.66278
G1 X20.199 Y34.627 E20.08096
M73 P61 R0
M73 Q61 S0
G1 X20.343 Y35.367 E20.22093
M73 P62 R0
M73 Q62 S0
G1 X20.058 Y35.243 E20.27862
G1 X19.797 Y35.077 E20.33615
G1 X19.394 Y34.733 E20.43439
G1 X18.999 Y34.327 E20.53961
M73 P63 R0
M73 Q63 S0
G1 X18.775 Y34.025 E20.60940
G1 X18.279 Y33.051 E20.81219
G1 X17.712 Y34.077 E21.02967
M73 P64 R0
M73 Q64 S0
G1 X17.564 Y34.456 E21.10513
G1 X17.374 Y35.124 E21.23405
M73 P65 R0
M73 Q65 S0
G1 X17.195 Y36.050 E21.40915
G1 X17.026 Y35.905 E21.45044
G1 X16.981 Y35.814 E21.46922
G1 X16.837 Y35.661 E21.50832
G1 X16.603 Y35.302 E21.58779
M73 P66 R0
M73 Q66 S0
G1 X16.481 Y35.045 E21.64060
G1 X16.395 Y34.748 E21.69797
G1 X16.326 Y34.700 E21.71369
G1 X16.208 Y34.367 E21.77924
G1 X16.044 Y33.757 E21.89631
G1 X15.939 Y33.024 E22.03373
M73 P67 R0
M73 Q67 S0
G1 X15.882 Y32.858 E22.06631
G1 X15.830 Y32.026 E22.22096
G1 X14.709 Y32.786 E22.47224
M73 P68 R0
M73 Q68 S0
G1 X14.581 Y32.970 E22.51385
G1 X14.368 Y32.173 E22.66692
M73 P69 R0
M73 Q69 S0
G1 X13.625 Y32.786 E22.84578
G1 X13.494 Y32.857 E22.87337
G1 X13.393 Y32.973 E22.90189
G1 X13.021 Y33.227 E22.98550
M73 P70 R0
M73 Q70 S0
G1 X13.166 Y32.905 E23.05116
G1 X11.648 Y33.283 E23.34154
M73 P71 R0
M73 Q71 S0
G1 X11.830 Y33.033 E23.39895
G1 X11.951 Y32.593 E23.48357
G1 X11.952 Y32.356 E23.52754
G1 X11.830 Y32.007 E23.59625
G1 X11.428 Y31.875 E23.67488
M73 P72 R0
M73 Q72 S0
G1 X8.957 Y32.474 E24.14672
M73 P73 R0
M73 Q73 S0
G1 X7.777 Y32.835 E24.37567
M73 P74 R0
M73 Q74 S0
G1 X7.643 Y32.907 E24.40376
G1 X7.313 Y33.029 E24.46909
G1 X6.990 Y33.189 E24.53597
G1 X6.985 Y32.889 E24.59159
G1 X6.010 Y32.983 E24.77351
M73 P75 R0
M73 Q75 S0
G1 X5.818 Y33.039 E24.81057
G1 X5.184 Y33.057 E24.92826
G1 X4.642 Y33.028 E25.02898
M73 P76 R0
M73 Q76 S0
G1 X4.565 Y32.835 E25.06756
G1 X4.515 Y32.508 E25.12894
G1 X4.426 Y32.245 E25.18050
G1 X3.925 Y31.743 E25.31200
G1 X3.883 Y31.546 E25.34950
G1 X3.737 Y31.480 E25.37916
M73 P77 R0
M73 Q77 S0
G1 X3.463 Y30.916 E25.49565
G1 X3.310 Y30.450 E25.58662
G1 X3.227 Y29.918 E25.68658
G1 X3.206 Y29.628 E25.74041
M73 P78 R0
M73 Q78 S0
G1 X3.203 Y28.743 E25.90473
G1 X3.256 Y27.771 E26.08543
G1 X4.176 Y27.614 E26.25854
M73 P79 R0
M73 Q79 S0
G1 X4.098 Y26.684 E26.43174
M73 P80 R0
M73 Q80 S0
G1 X3.881 Y25.714 E26.61613
G1 X3.874 Y24.700 E26.80428
M73 P81 R0
M73 Q81 S0
G1 X3.898 Y24.478 E26.84570
G1 X4.050 Y23.743 E26.98508
G1 X4.347 Y22.861 E27.15785
M73 P82 R0
M73 Q82 S0
G1 X4.485 Y22.534 E27.22366
G1 X4.522 Y22.625 E27.24184
G1 X4.603 Y22.725 E27.26580
G1 X4.908 Y23.267 E27.38110
G1 X5.023 Y23.364 E27.40901
G1 X5.079 Y23.463 E27.43019
G1 X5.990 Y24.470 E27.68212
M73 P83 R0
M73 Q83 S0
G1 X6.747 Y24.152 E27.83452
G1 X6.613 Y23.365 E27.98280
M73 P84 R0
M73 Q84 S0
G1 X7.133 Y23.508 E28.08296
G1 X7.277 Y23.589 E28.11359
G1 X7.621 Y23.711 E28.18131
M73 P85 R0
M73 Q85 S0
G1 X8.084 Y23.965 E28.27925
G1 X8.153 Y23.986 E28.29262
G1 X8.421 Y24.153 E28.35132
G1 X8.475 Y24.263 E28.37397
G1 X8.701 Y24.338 E28.41826
G1 X9.313 Y24.838 E28.56491
M73 P86 R0
M73 Q86 S0
G1 X9.872 Y25.036 E28.67483
G1 X10.255 Y24.413 E28.81059
G1 X10.461 Y23.943 E28.90590
M73 P87 R0
M73 Q87 S0
G1 X10.646 Y23.412 E29.01021
G1 X10.732 Y22.996 E29.08896
G1 X10.779 Y22.927 E29.10461
G1 X10.830 Y22.691 E29.14926
G1 X10.901 Y21.717 E29.33055
M73 P88 R0
M73 Q88 S0
G1 X10.934 Y19.802 E29.68597
M73 P89 R0
M73 Q89 S0
G1 X10.709 Y19.711 E29.73089
G1 X10.522 Y19.463 E29.78865
G1 X10.368 Y19.194 E29.84617
G1 X10.309 Y19.152 E29.85959
G1 X9.830 Y18.449 E30.01739
M73 P90 R0
M73 Q90 S0
G1 X9.426 Y17.787 E30.16126
G1 X9.189 Y17.312 E30.25978
G1 X9.118 Y17.066 E30.30735
G1 X9.084 Y16.754 E30.36556
M73 P91 R0
M73 Q91 S0
G1 X9.097 Y16.430 E30.42584
G1 X9.141 Y16.205 E30.46835
G1 X9.335 Y15.622 E30.58232
G1 X10.057 Y14.269 E30.86695
M73 P92 R0
M73 Q92 S0
G1 X10.412 Y13.112 E31.09155
M73 P93 R0
M73 Q93 S0
G1 X10.974 Y13.747 E31.24895
G1 X11.196 Y12.445 E31.49418
M73 P94 R0
M73 Q94 S0
G1 X11.288 Y12.108 E31.55885
G1 X11.405 Y11.822 E31.61624
G1 X11.856 Y11.930 E31.70222
G1 X12.008 Y11.651 E31.76134
M73 P95 R0
M73 Q95 S0
G1 X12.008 Y11.675 E31.76587
G1 X13.014 Y10.720 E32.02336
G1 X13.516 Y10.119 E32.16856
M73 P96 R0
M73 Q96 S0
G1 X13.821 Y9.678 E32.26814
G1 X13.902 Y9.599 E32.28911
G1 X14.028 Y9.362 E32.33887
G1 X14.113 Y9.256 E32.36414
G1 X14.342 Y8.815 E32.45642
M73 P97 R0
M73 Q97 S0
G1 X14.414 Y8.543 E32.50861
G1 X14.479 Y7.953 E32.61867
G1 X14.483 Y7.275 E32.74458
G1 X14.416 Y6.628 E32.86523
M73 P98 R0
M73 Q98 S0
G1 X14.304 Y6.202 E32.94704
G1 X14.211 Y6.023 E32.98440
G1 X14.026 Y5.810 E33.03671
G1 X13.717 Y5.592 E33.10694
G1 X13.806 Y5.269 E33.16924
M73 P99 R0
M73 Q99 S0
G1 X13.150 Y4.910 E33.30792
G1 X13.074 Y4.840 E33.32713
G1 X12.891 Y4.739 E33.36600
G1 X12.927 Y4.658 E33.38252
G1 X12.671 Y4.403 E33.44946
G92 E0
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
G4 ; wait
G28
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 33.45
; filament used [cm3] = 0.08
; total filament used [g] = 0.00
; total filament cost = 0.00
; estimated printing time (normal mode) = 13s
; estimated printing time (silent mode) = 13s

; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,120x0,120x120,0x120
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;\n;WITNESS ME\n;AND DELETE AFTER HERE FOR PANCAKES\n;\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 30
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 0
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = G4 ; wait\nG28
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = pancake
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 0.5
; first_layer_speed = 15
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; gap_fill_speed = 0
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 0
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0%
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 20
; inherits_cummulative = ;;"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.5
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 400,400
; machine_max_acceleration_extruding = 400,400
; machine_max_acceleration_retracting = 400,400
; machine_max_acceleration_x = 400,400
; machine_max_acceleration_y = 400,400
; machine_max_acceleration_z = 400,400
; machine_max_feedrate_e = 50,50
; machine_max_feedrate_x = 40,40
; machine_max_feedrate_y = 40,40
; machine_max_feedrate_z = 40,40
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 1
; max_print_height = 210
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; notes = 
; nozzle_diameter = 6
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 15
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = pancake
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = pancake
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 0
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 0
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0%
; solid_infill_speed = 20
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G90 ; use absolute coordinates\nM83 ; extruder relative mode\nG28\nG1 E1.5\nG92 E0.0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 45
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 200
; template_custom_gcode = 
; thin_walls = 0
; threads = 12
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0%
; top_solid_infill_speed = 15
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_speed = 20
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
